// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44324' | (string & {});
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type HealthStatusModel = 'Healthy' | 'Rebuilding' | 'Corrupted' | 'Empty' | 'Unknown';

export type IndexModel = {
    indexAlias: string;
    documentCount: number;
    healthStatus: HealthStatusModel;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedIndexModel = {
    total: number;
    items: Array<IndexModel>;
};

export type IndexesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/search/api/v1/indexes';
};

export type IndexesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type IndexesResponses = {
    /**
     * OK
     */
    200: PagedIndexModel;
};

export type IndexesResponse = IndexesResponses[keyof IndexesResponses];

export type RebuildData = {
    body?: never;
    path?: never;
    query?: {
        indexAlias?: string;
    };
    url: '/umbraco/search/api/v1/rebuild';
};

export type RebuildErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type RebuildResponses = {
    /**
     * OK
     */
    200: unknown;
};
